spring.application.name=backend_nhac


spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3306/seu_banco_local}
spring.datasource.username=${DB_USER:seu_usuario-do-db}
spring.datasource.password=${DB_PASS:sua-senha-do-db}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
api.security.token.secret=${JWT_SENHA:senha_jwt_secretassa}

spring.jpa.show-sql=true

spring.profiles.active=dev