spring.application.name=backend_nhac


spring.datasource.url=jdbc:mariadb://localhost:3306/nhac_db
spring.datasource.username=root
spring.datasource.password=157443
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver