spring.application.name=backend_nhac


spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3306/nhac_db}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:senai2026}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
api.security.token.secret=${JWT_SENHA:minha_chave_secreta_local_muito_segura_12345}
spring.jpa.show-sql=true
spring.flyway.out-of-order=true
google.client.id=${CLIENT_GOOGLE_ID:google_cloud_client_id}
twilio.account-sid=${TWILIO_SID:seu_twilio_sid}
twilio.auth-token=${AUTH_TOKEN:seu_twilio_auth_token}
twilio.from-number=${NUMBER:numero}
nhac.sms.mock-mode=true

# Stripe Configuration
stripe.api.key=${STRIPE_API_KEY:sk_test_12345}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET:whsec_12345}

spring.profiles.active=dev