ALTER TABLE tb_usuarios
ADD COLUMN notificar_novo_pedido BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN notificar_mensagens BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN notificar_avaliacoes BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN notificar_novidades BOOLEAN NOT NULL DEFAULT FALSE;
